# Sequences
sequences:
  - name: "coal"
    region: "coal-region"
    sequence:
      - COAL_ORE
      - STONE
      - COBBLESTONE
    # Delay in seconds from bedrock -> first block
    delay: 5
  - name: "iron"
    region: "coal-region"
    sequence:
      - IRON_ORE
      - STONE
      - COBBLESTONE
    delay: 10
