# Blocks
blocks:
  coal_ore:
    # Replace block
    replace: stone
    # Delay in seconds
    delay: 300
  stone:
    replace: cobblestone
    delay: 300
  cobblestone:
    replace: bedrock
    delay: 10

regions:
  - coalmine
  - ironmine